/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IndividualCreateEventPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndividualCreateEventPayload{}

// IndividualCreateEventPayload IndividualCreateEventPayload generic structure
type IndividualCreateEventPayload struct {
	Individual *Individual `json:"individual,omitempty"`
}

// NewIndividualCreateEventPayload instantiates a new IndividualCreateEventPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndividualCreateEventPayload() *IndividualCreateEventPayload {
	this := IndividualCreateEventPayload{}
	return &this
}

// NewIndividualCreateEventPayloadWithDefaults instantiates a new IndividualCreateEventPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndividualCreateEventPayloadWithDefaults() *IndividualCreateEventPayload {
	this := IndividualCreateEventPayload{}
	return &this
}

// GetIndividual returns the Individual field value if set, zero value otherwise.
func (o *IndividualCreateEventPayload) GetIndividual() Individual {
	if o == nil || IsNil(o.Individual) {
		var ret Individual
		return ret
	}
	return *o.Individual
}

// GetIndividualOk returns a tuple with the Individual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualCreateEventPayload) GetIndividualOk() (*Individual, bool) {
	if o == nil || IsNil(o.Individual) {
		return nil, false
	}
	return o.Individual, true
}

// HasIndividual returns a boolean if a field has been set.
func (o *IndividualCreateEventPayload) HasIndividual() bool {
	if o != nil && !IsNil(o.Individual) {
		return true
	}

	return false
}

// SetIndividual gets a reference to the given Individual and assigns it to the Individual field.
func (o *IndividualCreateEventPayload) SetIndividual(v Individual) {
	o.Individual = &v
}

func (o IndividualCreateEventPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndividualCreateEventPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Individual) {
		toSerialize["individual"] = o.Individual
	}
	return toSerialize, nil
}

type NullableIndividualCreateEventPayload struct {
	value *IndividualCreateEventPayload
	isSet bool
}

func (v NullableIndividualCreateEventPayload) Get() *IndividualCreateEventPayload {
	return v.value
}

func (v *NullableIndividualCreateEventPayload) Set(val *IndividualCreateEventPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIndividualCreateEventPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIndividualCreateEventPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndividualCreateEventPayload(val *IndividualCreateEventPayload) *NullableIndividualCreateEventPayload {
	return &NullableIndividualCreateEventPayload{value: val, isSet: true}
}

func (v NullableIndividualCreateEventPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndividualCreateEventPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


