/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartyRoleRefMVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartyRoleRefMVO{}

// PartyRoleRefMVO struct for PartyRoleRefMVO
type PartyRoleRefMVO struct {
	// When sub-classing, this defines the sub-class Extensible name
	Type string `json:"@type"`
	// When sub-classing, this defines the super-class
	BaseType *string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation *string `json:"@schemaLocation,omitempty"`
	// The URI of the referred entity.
	Href *string `json:"href,omitempty"`
	// The identifier of the referred entity.
	Id string `json:"id"`
	// Name of the referred entity.
	Name *string `json:"name,omitempty"`
	// The actual type of the target instance when needed for disambiguation.
	ReferredType *string `json:"@referredType,omitempty"`
	// The identifier of the engaged party that is linked to the PartyRole object.
	PartyId *string `json:"partyId,omitempty"`
	// The name of the engaged party that is linked to the PartyRole object.
	PartyName *string `json:"partyName,omitempty"`
}

type _PartyRoleRefMVO PartyRoleRefMVO

// NewPartyRoleRefMVO instantiates a new PartyRoleRefMVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartyRoleRefMVO(type_ string, id string) *PartyRoleRefMVO {
	this := PartyRoleRefMVO{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewPartyRoleRefMVOWithDefaults instantiates a new PartyRoleRefMVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartyRoleRefMVOWithDefaults() *PartyRoleRefMVO {
	this := PartyRoleRefMVO{}
	return &this
}

// GetType returns the Type field value
func (o *PartyRoleRefMVO) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PartyRoleRefMVO) SetType(v string) {
	o.Type = v
}

// GetBaseType returns the BaseType field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetBaseType() string {
	if o == nil || IsNil(o.BaseType) {
		var ret string
		return ret
	}
	return *o.BaseType
}

// GetBaseTypeOk returns a tuple with the BaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetBaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BaseType) {
		return nil, false
	}
	return o.BaseType, true
}

// HasBaseType returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasBaseType() bool {
	if o != nil && !IsNil(o.BaseType) {
		return true
	}

	return false
}

// SetBaseType gets a reference to the given string and assigns it to the BaseType field.
func (o *PartyRoleRefMVO) SetBaseType(v string) {
	o.BaseType = &v
}

// GetSchemaLocation returns the SchemaLocation field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetSchemaLocation() string {
	if o == nil || IsNil(o.SchemaLocation) {
		var ret string
		return ret
	}
	return *o.SchemaLocation
}

// GetSchemaLocationOk returns a tuple with the SchemaLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetSchemaLocationOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaLocation) {
		return nil, false
	}
	return o.SchemaLocation, true
}

// HasSchemaLocation returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasSchemaLocation() bool {
	if o != nil && !IsNil(o.SchemaLocation) {
		return true
	}

	return false
}

// SetSchemaLocation gets a reference to the given string and assigns it to the SchemaLocation field.
func (o *PartyRoleRefMVO) SetSchemaLocation(v string) {
	o.SchemaLocation = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *PartyRoleRefMVO) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value
func (o *PartyRoleRefMVO) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PartyRoleRefMVO) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PartyRoleRefMVO) SetName(v string) {
	o.Name = &v
}

// GetReferredType returns the ReferredType field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetReferredType() string {
	if o == nil || IsNil(o.ReferredType) {
		var ret string
		return ret
	}
	return *o.ReferredType
}

// GetReferredTypeOk returns a tuple with the ReferredType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetReferredTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ReferredType) {
		return nil, false
	}
	return o.ReferredType, true
}

// HasReferredType returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasReferredType() bool {
	if o != nil && !IsNil(o.ReferredType) {
		return true
	}

	return false
}

// SetReferredType gets a reference to the given string and assigns it to the ReferredType field.
func (o *PartyRoleRefMVO) SetReferredType(v string) {
	o.ReferredType = &v
}

// GetPartyId returns the PartyId field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetPartyId() string {
	if o == nil || IsNil(o.PartyId) {
		var ret string
		return ret
	}
	return *o.PartyId
}

// GetPartyIdOk returns a tuple with the PartyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetPartyIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartyId) {
		return nil, false
	}
	return o.PartyId, true
}

// HasPartyId returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasPartyId() bool {
	if o != nil && !IsNil(o.PartyId) {
		return true
	}

	return false
}

// SetPartyId gets a reference to the given string and assigns it to the PartyId field.
func (o *PartyRoleRefMVO) SetPartyId(v string) {
	o.PartyId = &v
}

// GetPartyName returns the PartyName field value if set, zero value otherwise.
func (o *PartyRoleRefMVO) GetPartyName() string {
	if o == nil || IsNil(o.PartyName) {
		var ret string
		return ret
	}
	return *o.PartyName
}

// GetPartyNameOk returns a tuple with the PartyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleRefMVO) GetPartyNameOk() (*string, bool) {
	if o == nil || IsNil(o.PartyName) {
		return nil, false
	}
	return o.PartyName, true
}

// HasPartyName returns a boolean if a field has been set.
func (o *PartyRoleRefMVO) HasPartyName() bool {
	if o != nil && !IsNil(o.PartyName) {
		return true
	}

	return false
}

// SetPartyName gets a reference to the given string and assigns it to the PartyName field.
func (o *PartyRoleRefMVO) SetPartyName(v string) {
	o.PartyName = &v
}

func (o PartyRoleRefMVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartyRoleRefMVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@type"] = o.Type
	if !IsNil(o.BaseType) {
		toSerialize["@baseType"] = o.BaseType
	}
	if !IsNil(o.SchemaLocation) {
		toSerialize["@schemaLocation"] = o.SchemaLocation
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ReferredType) {
		toSerialize["@referredType"] = o.ReferredType
	}
	if !IsNil(o.PartyId) {
		toSerialize["partyId"] = o.PartyId
	}
	if !IsNil(o.PartyName) {
		toSerialize["partyName"] = o.PartyName
	}
	return toSerialize, nil
}

func (o *PartyRoleRefMVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartyRoleRefMVO := _PartyRoleRefMVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartyRoleRefMVO)

	if err != nil {
		return err
	}

	*o = PartyRoleRefMVO(varPartyRoleRefMVO)

	return err
}

type NullablePartyRoleRefMVO struct {
	value *PartyRoleRefMVO
	isSet bool
}

func (v NullablePartyRoleRefMVO) Get() *PartyRoleRefMVO {
	return v.value
}

func (v *NullablePartyRoleRefMVO) Set(val *PartyRoleRefMVO) {
	v.value = val
	v.isSet = true
}

func (v NullablePartyRoleRefMVO) IsSet() bool {
	return v.isSet
}

func (v *NullablePartyRoleRefMVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartyRoleRefMVO(val *PartyRoleRefMVO) *NullablePartyRoleRefMVO {
	return &NullablePartyRoleRefMVO{value: val, isSet: true}
}

func (v NullablePartyRoleRefMVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartyRoleRefMVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


