/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartyRoleFVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartyRoleFVO{}

// PartyRoleFVO struct for PartyRoleFVO
type PartyRoleFVO struct {
	// When sub-classing, this defines the sub-class Extensible name
	Type string `json:"@type"`
	// When sub-classing, this defines the super-class
	BaseType *string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation *string `json:"@schemaLocation,omitempty"`
	// unique identifier
	Id *string `json:"id,omitempty"`
	// A word, term, or phrase by which the PartyRole is known and distinguished from other PartyRoles. It's the name of the PartyRole unique entity.
	Name string `json:"name"`
	// A description of the PartyRole.
	Description *string `json:"description,omitempty"`
	// Role played by the engagedParty in this context. As role is defined by partyRoleSpecification, this role attribute can be used to precise the role defined by partyRoleSpecification, or it can be used to define the role in case there is no partyRoleSpecification.
	Role *string `json:"role,omitempty"`
	EngagedParty PartyRefFVO `json:"engagedParty"`
	PartyRoleSpecification *PartyRoleSpecificationRefFVO `json:"partyRoleSpecification,omitempty"`
	// Describes the characteristic of a party role.
	Characteristic []CharacteristicFVO `json:"characteristic,omitempty"`
	Account []AccountRefFVO `json:"account,omitempty"`
	Agreement []AgreementRefFVO `json:"agreement,omitempty"`
	ContactMedium []ContactMediumFVO `json:"contactMedium,omitempty"`
	PaymentMethod []PaymentMethodRefFVO `json:"paymentMethod,omitempty"`
	CreditProfile []CreditProfileFVO `json:"creditProfile,omitempty"`
	RelatedParty []RelatedPartyOrPartyRoleFVO `json:"relatedParty,omitempty"`
	// Used to track the lifecycle status of the party role.
	Status *string `json:"status,omitempty"`
	// A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.
	StatusReason *string `json:"statusReason,omitempty"`
	ValidFor *TimePeriod `json:"validFor,omitempty"`
}

type _PartyRoleFVO PartyRoleFVO

// NewPartyRoleFVO instantiates a new PartyRoleFVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartyRoleFVO(type_ string, name string, engagedParty PartyRefFVO) *PartyRoleFVO {
	this := PartyRoleFVO{}
	this.Type = type_
	this.Name = name
	this.EngagedParty = engagedParty
	return &this
}

// NewPartyRoleFVOWithDefaults instantiates a new PartyRoleFVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartyRoleFVOWithDefaults() *PartyRoleFVO {
	this := PartyRoleFVO{}
	return &this
}

// GetType returns the Type field value
func (o *PartyRoleFVO) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PartyRoleFVO) SetType(v string) {
	o.Type = v
}

// GetBaseType returns the BaseType field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetBaseType() string {
	if o == nil || IsNil(o.BaseType) {
		var ret string
		return ret
	}
	return *o.BaseType
}

// GetBaseTypeOk returns a tuple with the BaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetBaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BaseType) {
		return nil, false
	}
	return o.BaseType, true
}

// HasBaseType returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasBaseType() bool {
	if o != nil && !IsNil(o.BaseType) {
		return true
	}

	return false
}

// SetBaseType gets a reference to the given string and assigns it to the BaseType field.
func (o *PartyRoleFVO) SetBaseType(v string) {
	o.BaseType = &v
}

// GetSchemaLocation returns the SchemaLocation field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetSchemaLocation() string {
	if o == nil || IsNil(o.SchemaLocation) {
		var ret string
		return ret
	}
	return *o.SchemaLocation
}

// GetSchemaLocationOk returns a tuple with the SchemaLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetSchemaLocationOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaLocation) {
		return nil, false
	}
	return o.SchemaLocation, true
}

// HasSchemaLocation returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasSchemaLocation() bool {
	if o != nil && !IsNil(o.SchemaLocation) {
		return true
	}

	return false
}

// SetSchemaLocation gets a reference to the given string and assigns it to the SchemaLocation field.
func (o *PartyRoleFVO) SetSchemaLocation(v string) {
	o.SchemaLocation = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PartyRoleFVO) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *PartyRoleFVO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PartyRoleFVO) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PartyRoleFVO) SetDescription(v string) {
	o.Description = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *PartyRoleFVO) SetRole(v string) {
	o.Role = &v
}

// GetEngagedParty returns the EngagedParty field value
func (o *PartyRoleFVO) GetEngagedParty() PartyRefFVO {
	if o == nil {
		var ret PartyRefFVO
		return ret
	}

	return o.EngagedParty
}

// GetEngagedPartyOk returns a tuple with the EngagedParty field value
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetEngagedPartyOk() (*PartyRefFVO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EngagedParty, true
}

// SetEngagedParty sets field value
func (o *PartyRoleFVO) SetEngagedParty(v PartyRefFVO) {
	o.EngagedParty = v
}

// GetPartyRoleSpecification returns the PartyRoleSpecification field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetPartyRoleSpecification() PartyRoleSpecificationRefFVO {
	if o == nil || IsNil(o.PartyRoleSpecification) {
		var ret PartyRoleSpecificationRefFVO
		return ret
	}
	return *o.PartyRoleSpecification
}

// GetPartyRoleSpecificationOk returns a tuple with the PartyRoleSpecification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetPartyRoleSpecificationOk() (*PartyRoleSpecificationRefFVO, bool) {
	if o == nil || IsNil(o.PartyRoleSpecification) {
		return nil, false
	}
	return o.PartyRoleSpecification, true
}

// HasPartyRoleSpecification returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasPartyRoleSpecification() bool {
	if o != nil && !IsNil(o.PartyRoleSpecification) {
		return true
	}

	return false
}

// SetPartyRoleSpecification gets a reference to the given PartyRoleSpecificationRefFVO and assigns it to the PartyRoleSpecification field.
func (o *PartyRoleFVO) SetPartyRoleSpecification(v PartyRoleSpecificationRefFVO) {
	o.PartyRoleSpecification = &v
}

// GetCharacteristic returns the Characteristic field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetCharacteristic() []CharacteristicFVO {
	if o == nil || IsNil(o.Characteristic) {
		var ret []CharacteristicFVO
		return ret
	}
	return o.Characteristic
}

// GetCharacteristicOk returns a tuple with the Characteristic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetCharacteristicOk() ([]CharacteristicFVO, bool) {
	if o == nil || IsNil(o.Characteristic) {
		return nil, false
	}
	return o.Characteristic, true
}

// HasCharacteristic returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasCharacteristic() bool {
	if o != nil && !IsNil(o.Characteristic) {
		return true
	}

	return false
}

// SetCharacteristic gets a reference to the given []CharacteristicFVO and assigns it to the Characteristic field.
func (o *PartyRoleFVO) SetCharacteristic(v []CharacteristicFVO) {
	o.Characteristic = v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetAccount() []AccountRefFVO {
	if o == nil || IsNil(o.Account) {
		var ret []AccountRefFVO
		return ret
	}
	return o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetAccountOk() ([]AccountRefFVO, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given []AccountRefFVO and assigns it to the Account field.
func (o *PartyRoleFVO) SetAccount(v []AccountRefFVO) {
	o.Account = v
}

// GetAgreement returns the Agreement field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetAgreement() []AgreementRefFVO {
	if o == nil || IsNil(o.Agreement) {
		var ret []AgreementRefFVO
		return ret
	}
	return o.Agreement
}

// GetAgreementOk returns a tuple with the Agreement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetAgreementOk() ([]AgreementRefFVO, bool) {
	if o == nil || IsNil(o.Agreement) {
		return nil, false
	}
	return o.Agreement, true
}

// HasAgreement returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasAgreement() bool {
	if o != nil && !IsNil(o.Agreement) {
		return true
	}

	return false
}

// SetAgreement gets a reference to the given []AgreementRefFVO and assigns it to the Agreement field.
func (o *PartyRoleFVO) SetAgreement(v []AgreementRefFVO) {
	o.Agreement = v
}

// GetContactMedium returns the ContactMedium field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetContactMedium() []ContactMediumFVO {
	if o == nil || IsNil(o.ContactMedium) {
		var ret []ContactMediumFVO
		return ret
	}
	return o.ContactMedium
}

// GetContactMediumOk returns a tuple with the ContactMedium field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetContactMediumOk() ([]ContactMediumFVO, bool) {
	if o == nil || IsNil(o.ContactMedium) {
		return nil, false
	}
	return o.ContactMedium, true
}

// HasContactMedium returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasContactMedium() bool {
	if o != nil && !IsNil(o.ContactMedium) {
		return true
	}

	return false
}

// SetContactMedium gets a reference to the given []ContactMediumFVO and assigns it to the ContactMedium field.
func (o *PartyRoleFVO) SetContactMedium(v []ContactMediumFVO) {
	o.ContactMedium = v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetPaymentMethod() []PaymentMethodRefFVO {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret []PaymentMethodRefFVO
		return ret
	}
	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetPaymentMethodOk() ([]PaymentMethodRefFVO, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given []PaymentMethodRefFVO and assigns it to the PaymentMethod field.
func (o *PartyRoleFVO) SetPaymentMethod(v []PaymentMethodRefFVO) {
	o.PaymentMethod = v
}

// GetCreditProfile returns the CreditProfile field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetCreditProfile() []CreditProfileFVO {
	if o == nil || IsNil(o.CreditProfile) {
		var ret []CreditProfileFVO
		return ret
	}
	return o.CreditProfile
}

// GetCreditProfileOk returns a tuple with the CreditProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetCreditProfileOk() ([]CreditProfileFVO, bool) {
	if o == nil || IsNil(o.CreditProfile) {
		return nil, false
	}
	return o.CreditProfile, true
}

// HasCreditProfile returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasCreditProfile() bool {
	if o != nil && !IsNil(o.CreditProfile) {
		return true
	}

	return false
}

// SetCreditProfile gets a reference to the given []CreditProfileFVO and assigns it to the CreditProfile field.
func (o *PartyRoleFVO) SetCreditProfile(v []CreditProfileFVO) {
	o.CreditProfile = v
}

// GetRelatedParty returns the RelatedParty field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetRelatedParty() []RelatedPartyOrPartyRoleFVO {
	if o == nil || IsNil(o.RelatedParty) {
		var ret []RelatedPartyOrPartyRoleFVO
		return ret
	}
	return o.RelatedParty
}

// GetRelatedPartyOk returns a tuple with the RelatedParty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetRelatedPartyOk() ([]RelatedPartyOrPartyRoleFVO, bool) {
	if o == nil || IsNil(o.RelatedParty) {
		return nil, false
	}
	return o.RelatedParty, true
}

// HasRelatedParty returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasRelatedParty() bool {
	if o != nil && !IsNil(o.RelatedParty) {
		return true
	}

	return false
}

// SetRelatedParty gets a reference to the given []RelatedPartyOrPartyRoleFVO and assigns it to the RelatedParty field.
func (o *PartyRoleFVO) SetRelatedParty(v []RelatedPartyOrPartyRoleFVO) {
	o.RelatedParty = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PartyRoleFVO) SetStatus(v string) {
	o.Status = &v
}

// GetStatusReason returns the StatusReason field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetStatusReason() string {
	if o == nil || IsNil(o.StatusReason) {
		var ret string
		return ret
	}
	return *o.StatusReason
}

// GetStatusReasonOk returns a tuple with the StatusReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetStatusReasonOk() (*string, bool) {
	if o == nil || IsNil(o.StatusReason) {
		return nil, false
	}
	return o.StatusReason, true
}

// HasStatusReason returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasStatusReason() bool {
	if o != nil && !IsNil(o.StatusReason) {
		return true
	}

	return false
}

// SetStatusReason gets a reference to the given string and assigns it to the StatusReason field.
func (o *PartyRoleFVO) SetStatusReason(v string) {
	o.StatusReason = &v
}

// GetValidFor returns the ValidFor field value if set, zero value otherwise.
func (o *PartyRoleFVO) GetValidFor() TimePeriod {
	if o == nil || IsNil(o.ValidFor) {
		var ret TimePeriod
		return ret
	}
	return *o.ValidFor
}

// GetValidForOk returns a tuple with the ValidFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartyRoleFVO) GetValidForOk() (*TimePeriod, bool) {
	if o == nil || IsNil(o.ValidFor) {
		return nil, false
	}
	return o.ValidFor, true
}

// HasValidFor returns a boolean if a field has been set.
func (o *PartyRoleFVO) HasValidFor() bool {
	if o != nil && !IsNil(o.ValidFor) {
		return true
	}

	return false
}

// SetValidFor gets a reference to the given TimePeriod and assigns it to the ValidFor field.
func (o *PartyRoleFVO) SetValidFor(v TimePeriod) {
	o.ValidFor = &v
}

func (o PartyRoleFVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartyRoleFVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@type"] = o.Type
	if !IsNil(o.BaseType) {
		toSerialize["@baseType"] = o.BaseType
	}
	if !IsNil(o.SchemaLocation) {
		toSerialize["@schemaLocation"] = o.SchemaLocation
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["engagedParty"] = o.EngagedParty
	if !IsNil(o.PartyRoleSpecification) {
		toSerialize["partyRoleSpecification"] = o.PartyRoleSpecification
	}
	if !IsNil(o.Characteristic) {
		toSerialize["characteristic"] = o.Characteristic
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Agreement) {
		toSerialize["agreement"] = o.Agreement
	}
	if !IsNil(o.ContactMedium) {
		toSerialize["contactMedium"] = o.ContactMedium
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["paymentMethod"] = o.PaymentMethod
	}
	if !IsNil(o.CreditProfile) {
		toSerialize["creditProfile"] = o.CreditProfile
	}
	if !IsNil(o.RelatedParty) {
		toSerialize["relatedParty"] = o.RelatedParty
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusReason) {
		toSerialize["statusReason"] = o.StatusReason
	}
	if !IsNil(o.ValidFor) {
		toSerialize["validFor"] = o.ValidFor
	}
	return toSerialize, nil
}

func (o *PartyRoleFVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@type",
		"name",
		"engagedParty",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartyRoleFVO := _PartyRoleFVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartyRoleFVO)

	if err != nil {
		return err
	}

	*o = PartyRoleFVO(varPartyRoleFVO)

	return err
}

type NullablePartyRoleFVO struct {
	value *PartyRoleFVO
	isSet bool
}

func (v NullablePartyRoleFVO) Get() *PartyRoleFVO {
	return v.value
}

func (v *NullablePartyRoleFVO) Set(val *PartyRoleFVO) {
	v.value = val
	v.isSet = true
}

func (v NullablePartyRoleFVO) IsSet() bool {
	return v.isSet
}

func (v *NullablePartyRoleFVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartyRoleFVO(val *PartyRoleFVO) *NullablePartyRoleFVO {
	return &NullablePartyRoleFVO{value: val, isSet: true}
}

func (v NullablePartyRoleFVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartyRoleFVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


