/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationChildRelationshipFVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationChildRelationshipFVO{}

// OrganizationChildRelationshipFVO struct for OrganizationChildRelationshipFVO
type OrganizationChildRelationshipFVO struct {
	// When sub-classing, this defines the sub-class Extensible name
	Type string `json:"@type"`
	// When sub-classing, this defines the super-class
	BaseType *string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation *string `json:"@schemaLocation,omitempty"`
	// Type of the relationship. Could be juridical, hierarchical, geographical, functional for example.
	RelationshipType *string `json:"relationshipType,omitempty"`
	Organization *OrganizationRefFVO `json:"organization,omitempty"`
}

type _OrganizationChildRelationshipFVO OrganizationChildRelationshipFVO

// NewOrganizationChildRelationshipFVO instantiates a new OrganizationChildRelationshipFVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationChildRelationshipFVO(type_ string) *OrganizationChildRelationshipFVO {
	this := OrganizationChildRelationshipFVO{}
	this.Type = type_
	return &this
}

// NewOrganizationChildRelationshipFVOWithDefaults instantiates a new OrganizationChildRelationshipFVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationChildRelationshipFVOWithDefaults() *OrganizationChildRelationshipFVO {
	this := OrganizationChildRelationshipFVO{}
	return &this
}

// GetType returns the Type field value
func (o *OrganizationChildRelationshipFVO) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OrganizationChildRelationshipFVO) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OrganizationChildRelationshipFVO) SetType(v string) {
	o.Type = v
}

// GetBaseType returns the BaseType field value if set, zero value otherwise.
func (o *OrganizationChildRelationshipFVO) GetBaseType() string {
	if o == nil || IsNil(o.BaseType) {
		var ret string
		return ret
	}
	return *o.BaseType
}

// GetBaseTypeOk returns a tuple with the BaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationChildRelationshipFVO) GetBaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BaseType) {
		return nil, false
	}
	return o.BaseType, true
}

// HasBaseType returns a boolean if a field has been set.
func (o *OrganizationChildRelationshipFVO) HasBaseType() bool {
	if o != nil && !IsNil(o.BaseType) {
		return true
	}

	return false
}

// SetBaseType gets a reference to the given string and assigns it to the BaseType field.
func (o *OrganizationChildRelationshipFVO) SetBaseType(v string) {
	o.BaseType = &v
}

// GetSchemaLocation returns the SchemaLocation field value if set, zero value otherwise.
func (o *OrganizationChildRelationshipFVO) GetSchemaLocation() string {
	if o == nil || IsNil(o.SchemaLocation) {
		var ret string
		return ret
	}
	return *o.SchemaLocation
}

// GetSchemaLocationOk returns a tuple with the SchemaLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationChildRelationshipFVO) GetSchemaLocationOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaLocation) {
		return nil, false
	}
	return o.SchemaLocation, true
}

// HasSchemaLocation returns a boolean if a field has been set.
func (o *OrganizationChildRelationshipFVO) HasSchemaLocation() bool {
	if o != nil && !IsNil(o.SchemaLocation) {
		return true
	}

	return false
}

// SetSchemaLocation gets a reference to the given string and assigns it to the SchemaLocation field.
func (o *OrganizationChildRelationshipFVO) SetSchemaLocation(v string) {
	o.SchemaLocation = &v
}

// GetRelationshipType returns the RelationshipType field value if set, zero value otherwise.
func (o *OrganizationChildRelationshipFVO) GetRelationshipType() string {
	if o == nil || IsNil(o.RelationshipType) {
		var ret string
		return ret
	}
	return *o.RelationshipType
}

// GetRelationshipTypeOk returns a tuple with the RelationshipType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationChildRelationshipFVO) GetRelationshipTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RelationshipType) {
		return nil, false
	}
	return o.RelationshipType, true
}

// HasRelationshipType returns a boolean if a field has been set.
func (o *OrganizationChildRelationshipFVO) HasRelationshipType() bool {
	if o != nil && !IsNil(o.RelationshipType) {
		return true
	}

	return false
}

// SetRelationshipType gets a reference to the given string and assigns it to the RelationshipType field.
func (o *OrganizationChildRelationshipFVO) SetRelationshipType(v string) {
	o.RelationshipType = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *OrganizationChildRelationshipFVO) GetOrganization() OrganizationRefFVO {
	if o == nil || IsNil(o.Organization) {
		var ret OrganizationRefFVO
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationChildRelationshipFVO) GetOrganizationOk() (*OrganizationRefFVO, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *OrganizationChildRelationshipFVO) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given OrganizationRefFVO and assigns it to the Organization field.
func (o *OrganizationChildRelationshipFVO) SetOrganization(v OrganizationRefFVO) {
	o.Organization = &v
}

func (o OrganizationChildRelationshipFVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationChildRelationshipFVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@type"] = o.Type
	if !IsNil(o.BaseType) {
		toSerialize["@baseType"] = o.BaseType
	}
	if !IsNil(o.SchemaLocation) {
		toSerialize["@schemaLocation"] = o.SchemaLocation
	}
	if !IsNil(o.RelationshipType) {
		toSerialize["relationshipType"] = o.RelationshipType
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	return toSerialize, nil
}

func (o *OrganizationChildRelationshipFVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationChildRelationshipFVO := _OrganizationChildRelationshipFVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationChildRelationshipFVO)

	if err != nil {
		return err
	}

	*o = OrganizationChildRelationshipFVO(varOrganizationChildRelationshipFVO)

	return err
}

type NullableOrganizationChildRelationshipFVO struct {
	value *OrganizationChildRelationshipFVO
	isSet bool
}

func (v NullableOrganizationChildRelationshipFVO) Get() *OrganizationChildRelationshipFVO {
	return v.value
}

func (v *NullableOrganizationChildRelationshipFVO) Set(val *OrganizationChildRelationshipFVO) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationChildRelationshipFVO) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationChildRelationshipFVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationChildRelationshipFVO(val *OrganizationChildRelationshipFVO) *NullableOrganizationChildRelationshipFVO {
	return &NullableOrganizationChildRelationshipFVO{value: val, isSet: true}
}

func (v NullableOrganizationChildRelationshipFVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationChildRelationshipFVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


