/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// PatchIndividual200Response - struct for PatchIndividual200Response
type PatchIndividual200Response struct {
	Individual *Individual
	ArrayOfIndividual *[]Individual
	String *string
}

// IndividualAsPatchIndividual200Response is a convenience function that returns Individual wrapped in PatchIndividual200Response
func IndividualAsPatchIndividual200Response(v *Individual) PatchIndividual200Response {
	return PatchIndividual200Response{
		Individual: v,
	}
}

// []IndividualAsPatchIndividual200Response is a convenience function that returns []Individual wrapped in PatchIndividual200Response
func ArrayOfIndividualAsPatchIndividual200Response(v *[]Individual) PatchIndividual200Response {
	return PatchIndividual200Response{
		ArrayOfIndividual: v,
	}
}

// stringAsPatchIndividual200Response is a convenience function that returns string wrapped in PatchIndividual200Response
func StringAsPatchIndividual200Response(v *string) PatchIndividual200Response {
	return PatchIndividual200Response{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchIndividual200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Individual
	err = newStrictDecoder(data).Decode(&dst.Individual)
	if err == nil {
		jsonIndividual, _ := json.Marshal(dst.Individual)
		if string(jsonIndividual) == "{}" { // empty struct
			dst.Individual = nil
		} else {
			if err = validator.Validate(dst.Individual); err != nil {
				dst.Individual = nil
			} else {
				match++
			}
		}
	} else {
		dst.Individual = nil
	}

	// try to unmarshal data into ArrayOfIndividual
	err = newStrictDecoder(data).Decode(&dst.ArrayOfIndividual)
	if err == nil {
		jsonArrayOfIndividual, _ := json.Marshal(dst.ArrayOfIndividual)
		if string(jsonArrayOfIndividual) == "{}" { // empty struct
			dst.ArrayOfIndividual = nil
		} else {
			if err = validator.Validate(dst.ArrayOfIndividual); err != nil {
				dst.ArrayOfIndividual = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfIndividual = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Individual = nil
		dst.ArrayOfIndividual = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchIndividual200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchIndividual200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchIndividual200Response) MarshalJSON() ([]byte, error) {
	if src.Individual != nil {
		return json.Marshal(&src.Individual)
	}

	if src.ArrayOfIndividual != nil {
		return json.Marshal(&src.ArrayOfIndividual)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchIndividual200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Individual != nil {
		return obj.Individual
	}

	if obj.ArrayOfIndividual != nil {
		return obj.ArrayOfIndividual
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePatchIndividual200Response struct {
	value *PatchIndividual200Response
	isSet bool
}

func (v NullablePatchIndividual200Response) Get() *PatchIndividual200Response {
	return v.value
}

func (v *NullablePatchIndividual200Response) Set(val *PatchIndividual200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchIndividual200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchIndividual200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchIndividual200Response(val *PatchIndividual200Response) *NullablePatchIndividual200Response {
	return &NullablePatchIndividual200Response{value: val, isSet: true}
}

func (v NullablePatchIndividual200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchIndividual200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


