/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IndividualIdentification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndividualIdentification{}

// IndividualIdentification struct for IndividualIdentification
type IndividualIdentification struct {
	// When sub-classing, this defines the sub-class Extensible name
	Type string `json:"@type"`
	// When sub-classing, this defines the super-class
	BaseType *string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation *string `json:"@schemaLocation,omitempty"`
	// Identifier
	IdentificationId *string `json:"identificationId,omitempty"`
	// Authority which has issued the identifier, such as: social security, town hall
	IssuingAuthority *string `json:"issuingAuthority,omitempty"`
	// Date at which the identifier was issued
	IssuingDate *time.Time `json:"issuingDate,omitempty"`
	// Identification type (passport, national identity card, drivers license, social security number, birth certificate)
	IdentificationType *string `json:"identificationType,omitempty"`
	ValidFor *TimePeriod `json:"validFor,omitempty"`
	Attachment *AttachmentRefOrValue `json:"attachment,omitempty"`
}

type _IndividualIdentification IndividualIdentification

// NewIndividualIdentification instantiates a new IndividualIdentification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndividualIdentification(type_ string) *IndividualIdentification {
	this := IndividualIdentification{}
	this.Type = type_
	return &this
}

// NewIndividualIdentificationWithDefaults instantiates a new IndividualIdentification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndividualIdentificationWithDefaults() *IndividualIdentification {
	this := IndividualIdentification{}
	return &this
}

// GetType returns the Type field value
func (o *IndividualIdentification) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IndividualIdentification) SetType(v string) {
	o.Type = v
}

// GetBaseType returns the BaseType field value if set, zero value otherwise.
func (o *IndividualIdentification) GetBaseType() string {
	if o == nil || IsNil(o.BaseType) {
		var ret string
		return ret
	}
	return *o.BaseType
}

// GetBaseTypeOk returns a tuple with the BaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetBaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BaseType) {
		return nil, false
	}
	return o.BaseType, true
}

// HasBaseType returns a boolean if a field has been set.
func (o *IndividualIdentification) HasBaseType() bool {
	if o != nil && !IsNil(o.BaseType) {
		return true
	}

	return false
}

// SetBaseType gets a reference to the given string and assigns it to the BaseType field.
func (o *IndividualIdentification) SetBaseType(v string) {
	o.BaseType = &v
}

// GetSchemaLocation returns the SchemaLocation field value if set, zero value otherwise.
func (o *IndividualIdentification) GetSchemaLocation() string {
	if o == nil || IsNil(o.SchemaLocation) {
		var ret string
		return ret
	}
	return *o.SchemaLocation
}

// GetSchemaLocationOk returns a tuple with the SchemaLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetSchemaLocationOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaLocation) {
		return nil, false
	}
	return o.SchemaLocation, true
}

// HasSchemaLocation returns a boolean if a field has been set.
func (o *IndividualIdentification) HasSchemaLocation() bool {
	if o != nil && !IsNil(o.SchemaLocation) {
		return true
	}

	return false
}

// SetSchemaLocation gets a reference to the given string and assigns it to the SchemaLocation field.
func (o *IndividualIdentification) SetSchemaLocation(v string) {
	o.SchemaLocation = &v
}

// GetIdentificationId returns the IdentificationId field value if set, zero value otherwise.
func (o *IndividualIdentification) GetIdentificationId() string {
	if o == nil || IsNil(o.IdentificationId) {
		var ret string
		return ret
	}
	return *o.IdentificationId
}

// GetIdentificationIdOk returns a tuple with the IdentificationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetIdentificationIdOk() (*string, bool) {
	if o == nil || IsNil(o.IdentificationId) {
		return nil, false
	}
	return o.IdentificationId, true
}

// HasIdentificationId returns a boolean if a field has been set.
func (o *IndividualIdentification) HasIdentificationId() bool {
	if o != nil && !IsNil(o.IdentificationId) {
		return true
	}

	return false
}

// SetIdentificationId gets a reference to the given string and assigns it to the IdentificationId field.
func (o *IndividualIdentification) SetIdentificationId(v string) {
	o.IdentificationId = &v
}

// GetIssuingAuthority returns the IssuingAuthority field value if set, zero value otherwise.
func (o *IndividualIdentification) GetIssuingAuthority() string {
	if o == nil || IsNil(o.IssuingAuthority) {
		var ret string
		return ret
	}
	return *o.IssuingAuthority
}

// GetIssuingAuthorityOk returns a tuple with the IssuingAuthority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetIssuingAuthorityOk() (*string, bool) {
	if o == nil || IsNil(o.IssuingAuthority) {
		return nil, false
	}
	return o.IssuingAuthority, true
}

// HasIssuingAuthority returns a boolean if a field has been set.
func (o *IndividualIdentification) HasIssuingAuthority() bool {
	if o != nil && !IsNil(o.IssuingAuthority) {
		return true
	}

	return false
}

// SetIssuingAuthority gets a reference to the given string and assigns it to the IssuingAuthority field.
func (o *IndividualIdentification) SetIssuingAuthority(v string) {
	o.IssuingAuthority = &v
}

// GetIssuingDate returns the IssuingDate field value if set, zero value otherwise.
func (o *IndividualIdentification) GetIssuingDate() time.Time {
	if o == nil || IsNil(o.IssuingDate) {
		var ret time.Time
		return ret
	}
	return *o.IssuingDate
}

// GetIssuingDateOk returns a tuple with the IssuingDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetIssuingDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.IssuingDate) {
		return nil, false
	}
	return o.IssuingDate, true
}

// HasIssuingDate returns a boolean if a field has been set.
func (o *IndividualIdentification) HasIssuingDate() bool {
	if o != nil && !IsNil(o.IssuingDate) {
		return true
	}

	return false
}

// SetIssuingDate gets a reference to the given time.Time and assigns it to the IssuingDate field.
func (o *IndividualIdentification) SetIssuingDate(v time.Time) {
	o.IssuingDate = &v
}

// GetIdentificationType returns the IdentificationType field value if set, zero value otherwise.
func (o *IndividualIdentification) GetIdentificationType() string {
	if o == nil || IsNil(o.IdentificationType) {
		var ret string
		return ret
	}
	return *o.IdentificationType
}

// GetIdentificationTypeOk returns a tuple with the IdentificationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetIdentificationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IdentificationType) {
		return nil, false
	}
	return o.IdentificationType, true
}

// HasIdentificationType returns a boolean if a field has been set.
func (o *IndividualIdentification) HasIdentificationType() bool {
	if o != nil && !IsNil(o.IdentificationType) {
		return true
	}

	return false
}

// SetIdentificationType gets a reference to the given string and assigns it to the IdentificationType field.
func (o *IndividualIdentification) SetIdentificationType(v string) {
	o.IdentificationType = &v
}

// GetValidFor returns the ValidFor field value if set, zero value otherwise.
func (o *IndividualIdentification) GetValidFor() TimePeriod {
	if o == nil || IsNil(o.ValidFor) {
		var ret TimePeriod
		return ret
	}
	return *o.ValidFor
}

// GetValidForOk returns a tuple with the ValidFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetValidForOk() (*TimePeriod, bool) {
	if o == nil || IsNil(o.ValidFor) {
		return nil, false
	}
	return o.ValidFor, true
}

// HasValidFor returns a boolean if a field has been set.
func (o *IndividualIdentification) HasValidFor() bool {
	if o != nil && !IsNil(o.ValidFor) {
		return true
	}

	return false
}

// SetValidFor gets a reference to the given TimePeriod and assigns it to the ValidFor field.
func (o *IndividualIdentification) SetValidFor(v TimePeriod) {
	o.ValidFor = &v
}

// GetAttachment returns the Attachment field value if set, zero value otherwise.
func (o *IndividualIdentification) GetAttachment() AttachmentRefOrValue {
	if o == nil || IsNil(o.Attachment) {
		var ret AttachmentRefOrValue
		return ret
	}
	return *o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualIdentification) GetAttachmentOk() (*AttachmentRefOrValue, bool) {
	if o == nil || IsNil(o.Attachment) {
		return nil, false
	}
	return o.Attachment, true
}

// HasAttachment returns a boolean if a field has been set.
func (o *IndividualIdentification) HasAttachment() bool {
	if o != nil && !IsNil(o.Attachment) {
		return true
	}

	return false
}

// SetAttachment gets a reference to the given AttachmentRefOrValue and assigns it to the Attachment field.
func (o *IndividualIdentification) SetAttachment(v AttachmentRefOrValue) {
	o.Attachment = &v
}

func (o IndividualIdentification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndividualIdentification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@type"] = o.Type
	if !IsNil(o.BaseType) {
		toSerialize["@baseType"] = o.BaseType
	}
	if !IsNil(o.SchemaLocation) {
		toSerialize["@schemaLocation"] = o.SchemaLocation
	}
	if !IsNil(o.IdentificationId) {
		toSerialize["identificationId"] = o.IdentificationId
	}
	if !IsNil(o.IssuingAuthority) {
		toSerialize["issuingAuthority"] = o.IssuingAuthority
	}
	if !IsNil(o.IssuingDate) {
		toSerialize["issuingDate"] = o.IssuingDate
	}
	if !IsNil(o.IdentificationType) {
		toSerialize["identificationType"] = o.IdentificationType
	}
	if !IsNil(o.ValidFor) {
		toSerialize["validFor"] = o.ValidFor
	}
	if !IsNil(o.Attachment) {
		toSerialize["attachment"] = o.Attachment
	}
	return toSerialize, nil
}

func (o *IndividualIdentification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndividualIdentification := _IndividualIdentification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIndividualIdentification)

	if err != nil {
		return err
	}

	*o = IndividualIdentification(varIndividualIdentification)

	return err
}

type NullableIndividualIdentification struct {
	value *IndividualIdentification
	isSet bool
}

func (v NullableIndividualIdentification) Get() *IndividualIdentification {
	return v.value
}

func (v *NullableIndividualIdentification) Set(val *IndividualIdentification) {
	v.value = val
	v.isSet = true
}

func (v NullableIndividualIdentification) IsSet() bool {
	return v.isSet
}

func (v *NullableIndividualIdentification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndividualIdentification(val *IndividualIdentification) *NullableIndividualIdentification {
	return &NullableIndividualIdentification{value: val, isSet: true}
}

func (v NullableIndividualIdentification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndividualIdentification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


