/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Party type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Party{}

// Party struct for Party
type Party struct {
	// When sub-classing, this defines the sub-class Extensible name
	Type string `json:"@type"`
	// When sub-classing, this defines the super-class
	BaseType *string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation *string `json:"@schemaLocation,omitempty"`
	// Hyperlink reference
	Href *string `json:"href,omitempty"`
	// unique identifier
	Id *string `json:"id,omitempty"`
	// List of identifiers of the Party in an external system, for example when party information is imported from a commerce system
	ExternalReference []ExternalIdentifier `json:"externalReference,omitempty"`
	// List of additional characteristics that a Party can take on.
	PartyCharacteristic []Characteristic `json:"partyCharacteristic,omitempty"`
	// List of tax exemptions granted to the party. For example, a war veteran might have partial exemption from state tax and a full exemption from federal tax
	TaxExemptionCertificate []TaxExemptionCertificate `json:"taxExemptionCertificate,omitempty"`
	// List of credit profiles and scores for the party, typically received from an external credit broker
	CreditRating []PartyCreditProfile `json:"creditRating,omitempty"`
	// List of parties and/or party roles related to this party
	RelatedParty []RelatedPartyOrPartyRole `json:"relatedParty,omitempty"`
	// List of means for contacting the party, e.g. mobile phone, email address
	ContactMedium []ContactMedium `json:"contactMedium,omitempty"`
}

type _Party Party

// NewParty instantiates a new Party object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParty(type_ string) *Party {
	this := Party{}
	this.Type = type_
	return &this
}

// NewPartyWithDefaults instantiates a new Party object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartyWithDefaults() *Party {
	this := Party{}
	return &this
}

// GetType returns the Type field value
func (o *Party) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Party) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Party) SetType(v string) {
	o.Type = v
}

// GetBaseType returns the BaseType field value if set, zero value otherwise.
func (o *Party) GetBaseType() string {
	if o == nil || IsNil(o.BaseType) {
		var ret string
		return ret
	}
	return *o.BaseType
}

// GetBaseTypeOk returns a tuple with the BaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetBaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BaseType) {
		return nil, false
	}
	return o.BaseType, true
}

// HasBaseType returns a boolean if a field has been set.
func (o *Party) HasBaseType() bool {
	if o != nil && !IsNil(o.BaseType) {
		return true
	}

	return false
}

// SetBaseType gets a reference to the given string and assigns it to the BaseType field.
func (o *Party) SetBaseType(v string) {
	o.BaseType = &v
}

// GetSchemaLocation returns the SchemaLocation field value if set, zero value otherwise.
func (o *Party) GetSchemaLocation() string {
	if o == nil || IsNil(o.SchemaLocation) {
		var ret string
		return ret
	}
	return *o.SchemaLocation
}

// GetSchemaLocationOk returns a tuple with the SchemaLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetSchemaLocationOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaLocation) {
		return nil, false
	}
	return o.SchemaLocation, true
}

// HasSchemaLocation returns a boolean if a field has been set.
func (o *Party) HasSchemaLocation() bool {
	if o != nil && !IsNil(o.SchemaLocation) {
		return true
	}

	return false
}

// SetSchemaLocation gets a reference to the given string and assigns it to the SchemaLocation field.
func (o *Party) SetSchemaLocation(v string) {
	o.SchemaLocation = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Party) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Party) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Party) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Party) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Party) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Party) SetId(v string) {
	o.Id = &v
}

// GetExternalReference returns the ExternalReference field value if set, zero value otherwise.
func (o *Party) GetExternalReference() []ExternalIdentifier {
	if o == nil || IsNil(o.ExternalReference) {
		var ret []ExternalIdentifier
		return ret
	}
	return o.ExternalReference
}

// GetExternalReferenceOk returns a tuple with the ExternalReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetExternalReferenceOk() ([]ExternalIdentifier, bool) {
	if o == nil || IsNil(o.ExternalReference) {
		return nil, false
	}
	return o.ExternalReference, true
}

// HasExternalReference returns a boolean if a field has been set.
func (o *Party) HasExternalReference() bool {
	if o != nil && !IsNil(o.ExternalReference) {
		return true
	}

	return false
}

// SetExternalReference gets a reference to the given []ExternalIdentifier and assigns it to the ExternalReference field.
func (o *Party) SetExternalReference(v []ExternalIdentifier) {
	o.ExternalReference = v
}

// GetPartyCharacteristic returns the PartyCharacteristic field value if set, zero value otherwise.
func (o *Party) GetPartyCharacteristic() []Characteristic {
	if o == nil || IsNil(o.PartyCharacteristic) {
		var ret []Characteristic
		return ret
	}
	return o.PartyCharacteristic
}

// GetPartyCharacteristicOk returns a tuple with the PartyCharacteristic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetPartyCharacteristicOk() ([]Characteristic, bool) {
	if o == nil || IsNil(o.PartyCharacteristic) {
		return nil, false
	}
	return o.PartyCharacteristic, true
}

// HasPartyCharacteristic returns a boolean if a field has been set.
func (o *Party) HasPartyCharacteristic() bool {
	if o != nil && !IsNil(o.PartyCharacteristic) {
		return true
	}

	return false
}

// SetPartyCharacteristic gets a reference to the given []Characteristic and assigns it to the PartyCharacteristic field.
func (o *Party) SetPartyCharacteristic(v []Characteristic) {
	o.PartyCharacteristic = v
}

// GetTaxExemptionCertificate returns the TaxExemptionCertificate field value if set, zero value otherwise.
func (o *Party) GetTaxExemptionCertificate() []TaxExemptionCertificate {
	if o == nil || IsNil(o.TaxExemptionCertificate) {
		var ret []TaxExemptionCertificate
		return ret
	}
	return o.TaxExemptionCertificate
}

// GetTaxExemptionCertificateOk returns a tuple with the TaxExemptionCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetTaxExemptionCertificateOk() ([]TaxExemptionCertificate, bool) {
	if o == nil || IsNil(o.TaxExemptionCertificate) {
		return nil, false
	}
	return o.TaxExemptionCertificate, true
}

// HasTaxExemptionCertificate returns a boolean if a field has been set.
func (o *Party) HasTaxExemptionCertificate() bool {
	if o != nil && !IsNil(o.TaxExemptionCertificate) {
		return true
	}

	return false
}

// SetTaxExemptionCertificate gets a reference to the given []TaxExemptionCertificate and assigns it to the TaxExemptionCertificate field.
func (o *Party) SetTaxExemptionCertificate(v []TaxExemptionCertificate) {
	o.TaxExemptionCertificate = v
}

// GetCreditRating returns the CreditRating field value if set, zero value otherwise.
func (o *Party) GetCreditRating() []PartyCreditProfile {
	if o == nil || IsNil(o.CreditRating) {
		var ret []PartyCreditProfile
		return ret
	}
	return o.CreditRating
}

// GetCreditRatingOk returns a tuple with the CreditRating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetCreditRatingOk() ([]PartyCreditProfile, bool) {
	if o == nil || IsNil(o.CreditRating) {
		return nil, false
	}
	return o.CreditRating, true
}

// HasCreditRating returns a boolean if a field has been set.
func (o *Party) HasCreditRating() bool {
	if o != nil && !IsNil(o.CreditRating) {
		return true
	}

	return false
}

// SetCreditRating gets a reference to the given []PartyCreditProfile and assigns it to the CreditRating field.
func (o *Party) SetCreditRating(v []PartyCreditProfile) {
	o.CreditRating = v
}

// GetRelatedParty returns the RelatedParty field value if set, zero value otherwise.
func (o *Party) GetRelatedParty() []RelatedPartyOrPartyRole {
	if o == nil || IsNil(o.RelatedParty) {
		var ret []RelatedPartyOrPartyRole
		return ret
	}
	return o.RelatedParty
}

// GetRelatedPartyOk returns a tuple with the RelatedParty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetRelatedPartyOk() ([]RelatedPartyOrPartyRole, bool) {
	if o == nil || IsNil(o.RelatedParty) {
		return nil, false
	}
	return o.RelatedParty, true
}

// HasRelatedParty returns a boolean if a field has been set.
func (o *Party) HasRelatedParty() bool {
	if o != nil && !IsNil(o.RelatedParty) {
		return true
	}

	return false
}

// SetRelatedParty gets a reference to the given []RelatedPartyOrPartyRole and assigns it to the RelatedParty field.
func (o *Party) SetRelatedParty(v []RelatedPartyOrPartyRole) {
	o.RelatedParty = v
}

// GetContactMedium returns the ContactMedium field value if set, zero value otherwise.
func (o *Party) GetContactMedium() []ContactMedium {
	if o == nil || IsNil(o.ContactMedium) {
		var ret []ContactMedium
		return ret
	}
	return o.ContactMedium
}

// GetContactMediumOk returns a tuple with the ContactMedium field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Party) GetContactMediumOk() ([]ContactMedium, bool) {
	if o == nil || IsNil(o.ContactMedium) {
		return nil, false
	}
	return o.ContactMedium, true
}

// HasContactMedium returns a boolean if a field has been set.
func (o *Party) HasContactMedium() bool {
	if o != nil && !IsNil(o.ContactMedium) {
		return true
	}

	return false
}

// SetContactMedium gets a reference to the given []ContactMedium and assigns it to the ContactMedium field.
func (o *Party) SetContactMedium(v []ContactMedium) {
	o.ContactMedium = v
}

func (o Party) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Party) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["@type"] = o.Type
	if !IsNil(o.BaseType) {
		toSerialize["@baseType"] = o.BaseType
	}
	if !IsNil(o.SchemaLocation) {
		toSerialize["@schemaLocation"] = o.SchemaLocation
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ExternalReference) {
		toSerialize["externalReference"] = o.ExternalReference
	}
	if !IsNil(o.PartyCharacteristic) {
		toSerialize["partyCharacteristic"] = o.PartyCharacteristic
	}
	if !IsNil(o.TaxExemptionCertificate) {
		toSerialize["taxExemptionCertificate"] = o.TaxExemptionCertificate
	}
	if !IsNil(o.CreditRating) {
		toSerialize["creditRating"] = o.CreditRating
	}
	if !IsNil(o.RelatedParty) {
		toSerialize["relatedParty"] = o.RelatedParty
	}
	if !IsNil(o.ContactMedium) {
		toSerialize["contactMedium"] = o.ContactMedium
	}
	return toSerialize, nil
}

func (o *Party) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"@type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParty := _Party{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParty)

	if err != nil {
		return err
	}

	*o = Party(varParty)

	return err
}

type NullableParty struct {
	value *Party
	isSet bool
}

func (v NullableParty) Get() *Party {
	return v.value
}

func (v *NullableParty) Set(val *Party) {
	v.value = val
	v.isSet = true
}

func (v NullableParty) IsSet() bool {
	return v.isSet
}

func (v *NullableParty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParty(val *Party) *NullableParty {
	return &NullableParty{value: val, isSet: true}
}

func (v NullableParty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


