/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationCreateEventPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationCreateEventPayload{}

// OrganizationCreateEventPayload OrganizationCreateEventPayload generic structure
type OrganizationCreateEventPayload struct {
	Organization *Organization `json:"organization,omitempty"`
}

// NewOrganizationCreateEventPayload instantiates a new OrganizationCreateEventPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationCreateEventPayload() *OrganizationCreateEventPayload {
	this := OrganizationCreateEventPayload{}
	return &this
}

// NewOrganizationCreateEventPayloadWithDefaults instantiates a new OrganizationCreateEventPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationCreateEventPayloadWithDefaults() *OrganizationCreateEventPayload {
	this := OrganizationCreateEventPayload{}
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *OrganizationCreateEventPayload) GetOrganization() Organization {
	if o == nil || IsNil(o.Organization) {
		var ret Organization
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationCreateEventPayload) GetOrganizationOk() (*Organization, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *OrganizationCreateEventPayload) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given Organization and assigns it to the Organization field.
func (o *OrganizationCreateEventPayload) SetOrganization(v Organization) {
	o.Organization = &v
}

func (o OrganizationCreateEventPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationCreateEventPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	return toSerialize, nil
}

type NullableOrganizationCreateEventPayload struct {
	value *OrganizationCreateEventPayload
	isSet bool
}

func (v NullableOrganizationCreateEventPayload) Get() *OrganizationCreateEventPayload {
	return v.value
}

func (v *NullableOrganizationCreateEventPayload) Set(val *OrganizationCreateEventPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationCreateEventPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationCreateEventPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationCreateEventPayload(val *OrganizationCreateEventPayload) *NullableOrganizationCreateEventPayload {
	return &NullableOrganizationCreateEventPayload{value: val, isSet: true}
}

func (v NullableOrganizationCreateEventPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationCreateEventPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


