/*
Party Management

TMF API Reference : TMF 632 - Party  Release: 22.5 The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion, and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3rd payer for a given offer and, then, allows consultation or update of his information. Resources - Party (abstract base class with concrete subclasses Individual and Organization) Party API performs the following operations: - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organization or individual

API version: 5.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Disability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Disability{}

// Disability Lack or inadequate strength or ability.
type Disability struct {
	// Code of the disability
	DisabilityCode *string `json:"disabilityCode,omitempty"`
	// Name of the disability
	DisabilityName *string `json:"disabilityName,omitempty"`
	ValidFor *TimePeriod `json:"validFor,omitempty"`
}

// NewDisability instantiates a new Disability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisability() *Disability {
	this := Disability{}
	return &this
}

// NewDisabilityWithDefaults instantiates a new Disability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisabilityWithDefaults() *Disability {
	this := Disability{}
	return &this
}

// GetDisabilityCode returns the DisabilityCode field value if set, zero value otherwise.
func (o *Disability) GetDisabilityCode() string {
	if o == nil || IsNil(o.DisabilityCode) {
		var ret string
		return ret
	}
	return *o.DisabilityCode
}

// GetDisabilityCodeOk returns a tuple with the DisabilityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disability) GetDisabilityCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DisabilityCode) {
		return nil, false
	}
	return o.DisabilityCode, true
}

// HasDisabilityCode returns a boolean if a field has been set.
func (o *Disability) HasDisabilityCode() bool {
	if o != nil && !IsNil(o.DisabilityCode) {
		return true
	}

	return false
}

// SetDisabilityCode gets a reference to the given string and assigns it to the DisabilityCode field.
func (o *Disability) SetDisabilityCode(v string) {
	o.DisabilityCode = &v
}

// GetDisabilityName returns the DisabilityName field value if set, zero value otherwise.
func (o *Disability) GetDisabilityName() string {
	if o == nil || IsNil(o.DisabilityName) {
		var ret string
		return ret
	}
	return *o.DisabilityName
}

// GetDisabilityNameOk returns a tuple with the DisabilityName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disability) GetDisabilityNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisabilityName) {
		return nil, false
	}
	return o.DisabilityName, true
}

// HasDisabilityName returns a boolean if a field has been set.
func (o *Disability) HasDisabilityName() bool {
	if o != nil && !IsNil(o.DisabilityName) {
		return true
	}

	return false
}

// SetDisabilityName gets a reference to the given string and assigns it to the DisabilityName field.
func (o *Disability) SetDisabilityName(v string) {
	o.DisabilityName = &v
}

// GetValidFor returns the ValidFor field value if set, zero value otherwise.
func (o *Disability) GetValidFor() TimePeriod {
	if o == nil || IsNil(o.ValidFor) {
		var ret TimePeriod
		return ret
	}
	return *o.ValidFor
}

// GetValidForOk returns a tuple with the ValidFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disability) GetValidForOk() (*TimePeriod, bool) {
	if o == nil || IsNil(o.ValidFor) {
		return nil, false
	}
	return o.ValidFor, true
}

// HasValidFor returns a boolean if a field has been set.
func (o *Disability) HasValidFor() bool {
	if o != nil && !IsNil(o.ValidFor) {
		return true
	}

	return false
}

// SetValidFor gets a reference to the given TimePeriod and assigns it to the ValidFor field.
func (o *Disability) SetValidFor(v TimePeriod) {
	o.ValidFor = &v
}

func (o Disability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Disability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisabilityCode) {
		toSerialize["disabilityCode"] = o.DisabilityCode
	}
	if !IsNil(o.DisabilityName) {
		toSerialize["disabilityName"] = o.DisabilityName
	}
	if !IsNil(o.ValidFor) {
		toSerialize["validFor"] = o.ValidFor
	}
	return toSerialize, nil
}

type NullableDisability struct {
	value *Disability
	isSet bool
}

func (v NullableDisability) Get() *Disability {
	return v.value
}

func (v *NullableDisability) Set(val *Disability) {
	v.value = val
	v.isSet = true
}

func (v NullableDisability) IsSet() bool {
	return v.isSet
}

func (v *NullableDisability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisability(val *Disability) *NullableDisability {
	return &NullableDisability{value: val, isSet: true}
}

func (v NullableDisability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


